panels:
- {id-panel: 'collapse-1',}
- {id-panel: 'collapse-2',}
- {id-panel: 'collapse-3',}
- {id-panel: 'collapse-4',}
- {id-panel: 'collapse-5',}
- {id-panel: 'collapse-6',}


number-line:
- {line: '1'}
- {line: '2'}
- {line: '3'}
- {line: '4'}
- {line: '5'}
- {line: '6'}
- {line: '7'}
- {line: '8'}
- {line: '9'}
- {line: '10'}